# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'question.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWebEngineWidgets import QWebEngineView

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(620, 518)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.jumpBt = QtWidgets.QPushButton(Dialog)
        self.jumpBt.setObjectName("jumpBt")
        self.gridLayout.addWidget(self.jumpBt, 0, 2, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(Dialog)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 0, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 3, 1, 2)
        self.sumLabel = QtWidgets.QLabel(Dialog)
        self.sumLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sumLabel.setObjectName("sumLabel")
        self.gridLayout.addWidget(self.sumLabel, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 6)
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 5, 3, 1, 3)
        # self.widget = QtWidgets.QWidget(Dialog)
        # self.widget.setObjectName("widget")
        self.browser = QWebEngineView()
        self.browser.setObjectName("webView")
        self.gridLayout.addWidget(self.browser, 4, 0, 1, 6)
        self.confirmBt = QtWidgets.QPushButton(Dialog)
        self.confirmBt.setObjectName("confirmBt")
        self.gridLayout.addWidget(self.confirmBt, 0, 5, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 5, 0, 1, 3)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 6, 3, 1, 3)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 6, 0, 1, 3)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit.setDragEnabled(False)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 8, 0, 1, 2)
        self.SearchBt = QtWidgets.QPushButton(Dialog)
        self.SearchBt.setEnabled(True)
        self.SearchBt.setObjectName("SearchBt")
        self.gridLayout.addWidget(self.SearchBt, 8, 2, 1, 1)
        self.SearchPrev = QtWidgets.QPushButton(Dialog)
        self.SearchPrev.setEnabled(True)
        self.SearchPrev.setObjectName("SearchPrev")
        self.gridLayout.addWidget(self.SearchPrev, 8, 3, 1, 1)
        self.numberLabel = QtWidgets.QLabel(Dialog)
        self.numberLabel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numberLabel.sizePolicy().hasHeightForWidth())
        self.numberLabel.setSizePolicy(sizePolicy)
        self.numberLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.numberLabel.setObjectName("numberLabel")
        self.gridLayout.addWidget(self.numberLabel, 8, 4, 1, 1)
        self.SearchNext = QtWidgets.QPushButton(Dialog)
        self.SearchNext.setEnabled(True)
        self.SearchNext.setObjectName("SearchNext")
        self.gridLayout.addWidget(self.SearchNext, 8, 5, 1, 1)
        self.KeySearchBt = QtWidgets.QPushButton(Dialog)
        self.KeySearchBt.setObjectName("KeySearchBt")
        self.gridLayout.addWidget(self.KeySearchBt, 7, 0, 1, 6)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Question Bank"))
        self.jumpBt.setText(_translate("Dialog", "题号跳转"))
        self.sumLabel.setText(_translate("Dialog", "总题数：0"))
        self.label.setText(_translate("Dialog", "等待出题..."))
        self.pushButton_4.setText(_translate("Dialog", "查看解析"))
        self.confirmBt.setText(_translate("Dialog", "确定"))
        self.pushButton_3.setText(_translate("Dialog", "下一题"))
        self.pushButton.setText(_translate("Dialog", "随机"))
        self.pushButton_2.setText(_translate("Dialog", "上一题"))
        self.SearchBt.setText(_translate("Dialog", "查询"))
        self.SearchPrev.setText(_translate("Dialog", "上一个"))
        self.numberLabel.setText(_translate("Dialog", "0/0"))
        self.SearchNext.setText(_translate("Dialog", "下一个"))
        self.KeySearchBt.setText(_translate("Dialog", "关键字查询"))
